FROM node:20-bullseye
# FROM node:20-bullseye

RUN apt-get update && apt-get install -y \
  git \
  curl \
  unzip \
  sudo \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# デフォルトユーザーの設定
USER node
